# Generated by Django 5.1.2 on 2024-10-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_complete_before_alter_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
